#include <windows.h>
#include <shlwapi.h>
#include <shellapi.h>
#include <wchar.h>
#include <stdio.h>
#include "WebView2.h"
#pragma comment(lib,"shlwapi.lib")
#pragma comment(lib,"shell32.lib")
#define IDI_APP_ICON 101
static HWND g_hwnd=NULL; static ICoreWebView2Controller *g_controller=NULL; static ICoreWebView2 *g_webview=NULL;
static wchar_t g_exe_dir[MAX_PATH*2],g_web_folder[MAX_PATH*2],g_cdn_folder[MAX_PATH*2],g_runtime_installer[MAX_PATH*2]; static int g_runtime_retry=0;
static void get_paths(void){DWORD n=GetModuleFileNameW(NULL,g_exe_dir,(DWORD)(sizeof(g_exe_dir)/sizeof(g_exe_dir[0])));if(!n||n>=sizeof(g_exe_dir)/sizeof(g_exe_dir[0]))return;PathRemoveFileSpecW(g_exe_dir);swprintf(g_web_folder,sizeof(g_web_folder)/sizeof(g_web_folder[0]),L"%s\\web",g_exe_dir);swprintf(g_cdn_folder,sizeof(g_cdn_folder)/sizeof(g_cdn_folder[0]),L"%s\\web\\cdnjs",g_exe_dir);swprintf(g_runtime_installer,sizeof(g_runtime_installer)/sizeof(g_runtime_installer[0]),L"%s\\MicrosoftEdgeWebView2RuntimeInstallerX64.exe",g_exe_dir);}
static void clear_webview_cache(void){wchar_t data[MAX_PATH*2];swprintf(data,sizeof(data)/sizeof(data[0]),L"%s\\WebView2Data",g_exe_dir);SHFILEOPSTRUCTW op={0};op.wFunc=FO_DELETE;op.pFrom=data;op.fFlags=FOF_NOCONFIRMATION|FOF_NOERRORUI|FOF_SILENT|FOF_ALLOWUNDO;SHFileOperationW(&op);}
static void resize_webview(void){if(!g_controller||!g_hwnd)return;RECT rc;GetClientRect(g_hwnd,&rc);ICoreWebView2Controller_put_Bounds(g_controller,rc);}
static HRESULT create_environment(void);
static void install_runtime_and_retry(void){if(g_runtime_retry||GetFileAttributesW(g_runtime_installer)==INVALID_FILE_ATTRIBUTES)return;g_runtime_retry=1;STARTUPINFOW si={0};PROCESS_INFORMATION pi={0};si.cb=sizeof(si);wchar_t cmd[MAX_PATH*2+64];swprintf(cmd,sizeof(cmd)/sizeof(cmd[0]),L"\"%s\" /silent /install",g_runtime_installer);if(CreateProcessW(NULL,cmd,NULL,NULL,FALSE,0,NULL,g_exe_dir,&si,&pi)){WaitForSingleObject(pi.hProcess,INFINITE);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);Sleep(1000);create_environment();}else MessageBoxW(g_hwnd,L"无法启动离线 WebView2 Runtime 安装程序。",L"PDF Bubble Annotator",MB_ICONERROR|MB_OK);}
typedef struct EnvHandler{ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler iface;}EnvHandler; typedef struct ControllerHandler{ICoreWebView2CreateCoreWebView2ControllerCompletedHandler iface;}ControllerHandler;
static HRESULT STDMETHODCALLTYPE Env_QueryInterface(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self,REFIID riid,void**ppv){if(!ppv)return E_POINTER;*ppv=NULL;if(IsEqualIID(riid,&IID_IUnknown)||IsEqualIID(riid,&IID_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler)){*ppv=self;ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler_AddRef(self);return S_OK;}return E_NOINTERFACE;} static ULONG STDMETHODCALLTYPE Env_AddRef(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self){(void)self;return 1;} static ULONG STDMETHODCALLTYPE Env_Release(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self){(void)self;return 1;}
static HRESULT STDMETHODCALLTYPE Controller_QueryInterface(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self,REFIID riid,void**ppv){if(!ppv)return E_POINTER;*ppv=NULL;if(IsEqualIID(riid,&IID_IUnknown)||IsEqualIID(riid,&IID_ICoreWebView2CreateCoreWebView2ControllerCompletedHandler)){*ppv=self;ICoreWebView2CreateCoreWebView2ControllerCompletedHandler_AddRef(self);return S_OK;}return E_NOINTERFACE;} static ULONG STDMETHODCALLTYPE Controller_AddRef(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self){(void)self;return 1;} static ULONG STDMETHODCALLTYPE Controller_Release(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self){(void)self;return 1;}
static HRESULT STDMETHODCALLTYPE Controller_Invoke(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self,HRESULT errorCode,ICoreWebView2Controller*controller){(void)self;if(FAILED(errorCode)||!controller){MessageBoxW(g_hwnd,L"WebView2 控件初始化失败。",L"PDF Bubble Annotator",MB_ICONERROR|MB_OK);return errorCode;}g_controller=controller;ICoreWebView2Controller_AddRef(g_controller);ICoreWebView2Controller_get_CoreWebView2(g_controller,&g_webview);if(!g_webview)return E_FAIL;ICoreWebView2_3 *web3=NULL;HRESULT mapHr=ICoreWebView2_QueryInterface(g_webview,&IID_ICoreWebView2_3,(void**)&web3);if(SUCCEEDED(mapHr)&&web3){ICoreWebView2_3_SetVirtualHostNameToFolderMapping(web3,L"pdfbubble.example",g_web_folder,COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW);ICoreWebView2_3_SetVirtualHostNameToFolderMapping(web3,L"cdnjs.cloudflare.com",g_cdn_folder,COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW);ICoreWebView2_3_Release(web3);}else{MessageBoxW(g_hwnd,L"当前 WebView2 SDK 不支持离线资源映射。",L"PDF Bubble Annotator",MB_ICONERROR|MB_OK);return E_NOINTERFACE;}resize_webview();ICoreWebView2_Navigate(g_webview,L"https://pdfbubble.example/index.html?v=0.5.60");SetTimer(g_hwnd,1001,1800,NULL);return S_OK;}
static ICoreWebView2CreateCoreWebView2ControllerCompletedHandlerVtbl g_controller_vtbl={Controller_QueryInterface,Controller_AddRef,Controller_Release,Controller_Invoke}; static ControllerHandler g_controller_handler={{&g_controller_vtbl}};
static HRESULT STDMETHODCALLTYPE Env_Invoke(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self,HRESULT errorCode,ICoreWebView2Environment*environment){(void)self;if(FAILED(errorCode)||!environment){install_runtime_and_retry();return errorCode;}return ICoreWebView2Environment_CreateCoreWebView2Controller(environment,g_hwnd,&g_controller_handler.iface);} static ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl g_env_vtbl={Env_QueryInterface,Env_AddRef,Env_Release,Env_Invoke}; static EnvHandler g_env_handler={{&g_env_vtbl}};
static HRESULT create_environment(void){wchar_t userDataFolder[MAX_PATH*2];swprintf(userDataFolder,sizeof(userDataFolder)/sizeof(userDataFolder[0]),L"%s\\WebView2Data",g_exe_dir);HRESULT hr=CreateCoreWebView2EnvironmentWithOptions(NULL,userDataFolder,NULL,&g_env_handler.iface);if(FAILED(hr))install_runtime_and_retry();return hr;}
static void init_webview(void){if(GetFileAttributesW(g_web_folder)==INVALID_FILE_ATTRIBUTES){MessageBoxW(g_hwnd,L"缺少 web 资源目录，安装包不完整。",L"PDF Bubble Annotator",MB_ICONERROR|MB_OK);return;}if(GetFileAttributesW(g_cdn_folder)==INVALID_FILE_ATTRIBUTES){MessageBoxW(g_hwnd,L"缺少离线依赖目录，安装包不完整。",L"PDF Bubble Annotator",MB_ICONERROR|MB_OK);return;}clear_webview_cache();create_environment();}
static LRESULT CALLBACK wnd_proc(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam){switch(msg){case WM_TIMER:if(wParam==1001){KillTimer(hwnd,1001);if(g_webview){ICoreWebView2_ExecuteScript(g_webview,L"(function(){try{if(window.caches&&caches.keys){caches.keys().then(function(k){k.forEach(function(x){caches.delete(x);});});}if(navigator.serviceWorker&&navigator.serviceWorker.getRegistrations){navigator.serviceWorker.getRegistrations().then(function(rs){rs.forEach(function(r){r.unregister();});});}localStorage.clear();sessionStorage.clear();}catch(e){}var a=document.createElement('script');a.src='/bugfix.js?v=0.5.60';a.onload=function(){var b=document.createElement('script');b.src='/ribbon-order.js?v=0.5.60';document.documentElement.appendChild(b);};document.documentElement.appendChild(a);})();",NULL);}return 0;}break;case WM_SIZE:resize_webview();return 0;case WM_DESTROY:if(g_webview){ICoreWebView2_Release(g_webview);g_webview=NULL;}if(g_controller){ICoreWebView2Controller_Release(g_controller);g_controller=NULL;}PostQuitMessage(0);return 0;}return DefWindowProcW(hwnd,msg,wParam,lParam);}
int WINAPI wWinMain(HINSTANCE hInstance,HINSTANCE hPrev,PWSTR lpCmdLine,int nCmdShow){(void)hPrev;(void)lpCmdLine;if(FAILED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)))return 1;get_paths();WNDCLASSEXW wc={0};wc.cbSize=sizeof(wc);wc.hInstance=hInstance;wc.lpfnWndProc=wnd_proc;wc.lpszClassName=L"PDFBubbleAnnotatorWindow";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hIcon=LoadIconW(hInstance,MAKEINTRESOURCEW(IDI_APP_ICON));wc.hIconSm=wc.hIcon;wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassExW(&wc);g_hwnd=CreateWindowExW(0,wc.lpszClassName,L"PDF Bubble Annotator - Bubble Drawing",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1280,900,NULL,NULL,hInstance,NULL);if(!g_hwnd){CoUninitialize();return 1;}ShowWindow(g_hwnd,nCmdShow);UpdateWindow(g_hwnd);init_webview();MSG msg;while(GetMessageW(&msg,NULL,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}CoUninitialize();return(int)msg.wParam;}