#include <windows.h>
#include <shlwapi.h>
#include <wchar.h>
#include "WebView2.h"
#pragma comment(lib, "shlwapi.lib")
#define IDI_APP_ICON 101
static HWND g_hwnd=NULL; static ICoreWebView2Controller *g_controller=NULL; static ICoreWebView2 *g_webview=NULL; static wchar_t g_start_page[MAX_PATH*2];
static void get_start_page(void){wchar_t exe[MAX_PATH*2];DWORD n=GetModuleFileNameW(NULL,exe,(DWORD)(sizeof(exe)/sizeof(exe[0])));if(!n||n>=sizeof(exe)/sizeof(exe[0]))return;PathRemoveFileSpecW(exe);swprintf(g_start_page,sizeof(g_start_page)/sizeof(g_start_page[0]),L"file:///%s/web/index.html",exe);for(wchar_t*p=g_start_page;*p;++p)if(*p==L'\\')*p=L'/';}
static void resize_webview(void){if(!g_controller||!g_hwnd)return;RECT rc;GetClientRect(g_hwnd,&rc);ICoreWebView2Controller_put_Bounds(g_controller,rc);}
typedef struct EnvHandler{ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler iface;}EnvHandler;
static HRESULT STDMETHODCALLTYPE Env_QueryInterface(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self,REFIID riid,void**ppv){if(!ppv)return E_POINTER;*ppv=NULL;if(IsEqualIID(riid,&IID_IUnknown)||IsEqualIID(riid,&IID_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler)){*ppv=self;ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler_AddRef(self);return S_OK;}return E_NOINTERFACE;}
static ULONG STDMETHODCALLTYPE Env_AddRef(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self){(void)self;return 1;} static ULONG STDMETHODCALLTYPE Env_Release(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self){(void)self;return 1;}
typedef struct ControllerHandler{ICoreWebView2CreateCoreWebView2ControllerCompletedHandler iface;}ControllerHandler;
static HRESULT STDMETHODCALLTYPE Controller_QueryInterface(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self,REFIID riid,void**ppv){if(!ppv)return E_POINTER;*ppv=NULL;if(IsEqualIID(riid,&IID_IUnknown)||IsEqualIID(riid,&IID_ICoreWebView2CreateCoreWebView2ControllerCompletedHandler)){*ppv=self;ICoreWebView2CreateCoreWebView2ControllerCompletedHandler_AddRef(self);return S_OK;}return E_NOINTERFACE;}
static ULONG STDMETHODCALLTYPE Controller_AddRef(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self){(void)self;return 1;} static ULONG STDMETHODCALLTYPE Controller_Release(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self){(void)self;return 1;}
static HRESULT STDMETHODCALLTYPE Controller_Invoke(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler*self,HRESULT errorCode,ICoreWebView2Controller*controller){(void)self;if(FAILED(errorCode)||!controller)return errorCode;g_controller=controller;ICoreWebView2Controller_AddRef(g_controller);ICoreWebView2Controller_get_CoreWebView2(g_controller,&g_webview);resize_webview();if(g_webview)ICoreWebView2_Navigate(g_webview,g_start_page);return S_OK;}
static ICoreWebView2CreateCoreWebView2ControllerCompletedHandlerVtbl g_controller_vtbl={Controller_QueryInterface,Controller_AddRef,Controller_Release,Controller_Invoke}; static ControllerHandler g_controller_handler={{&g_controller_vtbl}};
static HRESULT STDMETHODCALLTYPE Env_Invoke(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*self,HRESULT errorCode,ICoreWebView2Environment*environment){(void)self;if(FAILED(errorCode)||!environment)return errorCode;return ICoreWebView2Environment_CreateCoreWebView2Controller(environment,g_hwnd,&g_controller_handler.iface);}
static ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl g_env_vtbl={Env_QueryInterface,Env_AddRef,Env_Release,Env_Invoke}; static EnvHandler g_env_handler={{&g_env_vtbl}};
static void init_webview(void){wchar_t userDataFolder[MAX_PATH*2],exe[MAX_PATH*2];DWORD n=GetModuleFileNameW(NULL,exe,(DWORD)(sizeof(exe)/sizeof(exe[0])));if(!n||n>=sizeof(exe)/sizeof(exe[0]))return;PathRemoveFileSpecW(exe);swprintf(userDataFolder,sizeof(userDataFolder)/sizeof(userDataFolder[0]),L"%s\\WebView2Data",exe);HRESULT hr=CreateCoreWebView2EnvironmentWithOptions(NULL,userDataFolder,NULL,&g_env_handler.iface);if(FAILED(hr))MessageBoxW(g_hwnd,L"无法启动 WebView2。请安装 Microsoft Edge WebView2 Runtime。",L"PDF 图纸气泡序号标注工具",MB_ICONERROR|MB_OK);}
static LRESULT CALLBACK wnd_proc(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam){switch(msg){case WM_SIZE:resize_webview();return 0;case WM_DESTROY:if(g_webview){ICoreWebView2_Release(g_webview);g_webview=NULL;}if(g_controller){ICoreWebView2Controller_Release(g_controller);g_controller=NULL;}PostQuitMessage(0);return 0;}return DefWindowProcW(hwnd,msg,wParam,lParam);}
int WINAPI wWinMain(HINSTANCE hInstance,HINSTANCE hPrev,PWSTR lpCmdLine,int nCmdShow){(void)hPrev;(void)lpCmdLine;if(FAILED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)))return 1;get_start_page();WNDCLASSEXW wc={0};wc.cbSize=sizeof(wc);wc.hInstance=hInstance;wc.lpfnWndProc=wnd_proc;wc.lpszClassName=L"PDFBubbleAnnotatorWindow";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hIcon=LoadIconW(hInstance,MAKEINTRESOURCEW(IDI_APP_ICON));wc.hIconSm=wc.hIcon;wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassExW(&wc);g_hwnd=CreateWindowExW(0,wc.lpszClassName,L"PDF 图纸气泡序号标注工具",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1280,900,NULL,NULL,hInstance,NULL);if(!g_hwnd){CoUninitialize();return 1;}ShowWindow(g_hwnd,nCmdShow);UpdateWindow(g_hwnd);init_webview();MSG msg;while(GetMessageW(&msg,NULL,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}CoUninitialize();return(int)msg.wParam;}
