(function(){
  'use strict';
  if(window.__pbaAnnotationSuite)return; window.__pbaAnnotationSuite=1;
  const status=s=>{const e=document.getElementById('status');if(e)e.textContent=s};
  let clipboard=null;
  function refresh(){try{renderAnnotations();updateStats();updateList();if(typeof updateProp==='function')updateProp()}catch(e){console.error(e)}}
  function copySelected(){if(!selected){alert('请先选择一个标注');return}clipboard=JSON.parse(JSON.stringify(selected));status('已复制当前标注')}
  function pasteSelected(){if(!clipboard){alert('剪贴板为空');return}if(typeof snap==='function')snap();const a=JSON.parse(JSON.stringify(clipboard));a.id=Date.now()+Math.floor(Math.random()*1000);a.page=pageNo;a.nx=Math.min(.99,Math.max(.01,(Number(a.nx)||.5)+.03));a.ny=Math.min(.99,Math.max(.01,(Number(a.ny)||.5)+.03));ann.push(a);selected=a;refresh();status('已粘贴标注')}
  function move(dx,dy){if(!selected){alert('请先选择一个标注');return}if(typeof snap==='function')snap();selected.nx=Math.min(.99,Math.max(.01,(Number(selected.nx)||.5)+dx));selected.ny=Math.min(.99,Math.max(.01,(Number(selected.ny)||.5)+dy));refresh();status('标注已移动')}
  function classify(){if(!selected){alert('请先选择一个标注');return}const v=prompt('标注分类：\n例如：尺寸 / 外观 / 材料 / 检验 / 修改',selected.category||'尺寸');if(v===null)return;if(typeof snap==='function')snap();selected.category=v.trim()||'未分类';refresh();status('分类已更新：'+selected.category)}
  function exportJson(){if(typeof downloadBlob!=='function')return;const data={version:'0.6',source:sourceName,pages:pdf?pdf.numPages:0,annotations:ann};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),(sourceName||'document.pdf').replace(/\.pdf$/i,'')+' - Markup.json')}
  function importJson(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files&&input.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.annotations))throw new Error('JSON 中没有 annotations 数组');if(typeof snap==='function')snap();ann=data.annotations.map((a,i)=>({...a,id:a.id||Date.now()+i}));selected=null;refresh();status('已导入 '+ann.length+' 个标注')}catch(e){alert('导入失败：'+e.message)}};input.click()}
  function addUI(){const p=document.querySelector('.workspace .panel');if(!p||document.querySelector('.pba-annotation-box'))return;const box=document.createElement('div');box.className='section pba-annotation-box';box.innerHTML='<h4>标注管理</h4><div class="tool-grid"><button id="pbaCopy">📋 复制标注<small>Ctrl+C</small></button><button id="pbaPaste">📌 粘贴标注<small>Ctrl+V</small></button><button id="pbaClass">🏷 标注分类<small>方便统计</small></button><button id="pbaImport">⬇ 导入标注<small>JSON</small></button><button id="pbaExport">⬆ 导出标注<small>JSON</small></button><button id="pbaLeft">← 左移<small>精细调整</small></button><button id="pbaRight">→ 右移<small>精细调整</small></button><button id="pbaUp">↑ 上移<small>精细调整</small></button><button id="pbaDown">↓ 下移<small>精细调整</small></button></div>';p.appendChild(box);box.querySelector('#pbaCopy').onclick=copySelected;box.querySelector('#pbaPaste').onclick=pasteSelected;box.querySelector('#pbaClass').onclick=classify;box.querySelector('#pbaImport').onclick=importJson;box.querySelector('#pbaExport').onclick=exportJson;box.querySelector('#pbaLeft').onclick=()=>move(-.002,0);box.querySelector('#pbaRight').onclick=()=>move(.002,0);box.querySelector('#pbaUp').onclick=()=>move(0,-.002);box.querySelector('#pbaDown').onclick=()=>move(0,.002)}
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'){if(selected){e.preventDefault();copySelected()}}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'){if(clipboard){e.preventDefault();pasteSelected()}}});
  window.PBAAnnotationSuite={copySelected,pasteSelected,classify,importJson,exportJson,move};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(addUI,300));else setTimeout(addUI,300);
})();